version: '3.9'
services:
  redis:
    container_name: bitcoinapi_cache
    image: redis
    command: redis-server --requirepass 123456
    ports:
      - 6379:6379
    networks:
      - bitcoinapi_network

  api:
    build: .
    container_name: bitcoinapi
    command: bash -c "npx ts-node src/api.ts"
    ports:
      - 3001:3001
    networks:
      - bitcoinapi_network

networks:
  bitcoinapi_network:
