version: '3.9'
services:
  redis:
    container_name: bitcoinapi_cache
    image: redis
    command: redis-server --requirepass 123456
    ports:
      - 6379:6379
    networks:
      - bitcoinapi_network

networks:
  bitcoinapi_network:
